/**
 * Infinity Legal ZA - LLM Service Layer
 * 
 * High-level legal-specific AI functions powered by free LLM APIs.
 * Each function uses appropriate system prompts tailored for South African law,
 * includes POPIA compliance reminders, supports provider fallback,
 * caches responses where appropriate, and tracks token usage.
 */

import {
  llmChat,
  getConversation,
  updateConversation,
  clearConversation,
  trimMessages,
  type LLMMessage,
  type LLMChatOptions,
  type LLMChatResult,
} from './llm-providers';

// ============================================
// SYSTEM PROMPTS
// ============================================

const LEGAL_CHAT_SYSTEM_PROMPT = `You are "Ask Infinity" — the AI legal assistant for Infinity Legal SA, a South African legal services firm. You specialise in South African law and provide general legal guidance.

KEY RULES:
- You are a South African legal information assistant, NOT a replacement for an attorney.
- Always clarify that your responses are general legal information and NOT legal advice.
- You are knowledgeable about South African law: the Constitution, LRA (Labour Relations Act), BCEA (Basic Conditions of Employment Act), NCA (National Credit Act), POPIA (Protection of Personal Information Act), CPA (Consumer Protection Act), the Criminal Procedure Act, the Divorce Act, the Children's Act, and other SA legislation.
- You can help users understand their rights, legal processes, and what steps they might take.
- When appropriate, recommend the user book a consultation with an Infinity Legal attorney for case-specific advice.
- Always be professional, empathetic, and clear. Use plain language.
- If a matter seems urgent (e.g. domestic violence, criminal charges, imminent eviction), advise the user to seek immediate legal help and provide relevant emergency resources.
- You understand SA legal terminology: CCMA, High Court, Magistrates Court, Labour Court, Constitutional Court, etc.
- Always respond in the same language the user writes in. If they write in isiZulu, Afrikaans, etc., respond in that language.
- Keep responses concise but thorough. Use bullet points when listing steps or options.
- Never invent laws, case law, or legal provisions. If unsure, say so and recommend consulting an attorney.

POPIA COMPLIANCE:
- Remind users that their personal information is processed in accordance with POPIA.
- Do not ask for or store sensitive personal information (ID numbers, bank details, etc.).
- If a user shares sensitive data, remind them not to share such information in chat and suggest a formal consultation.

PRACTICE AREAS you can discuss:
1. Civil Litigation — consumer disputes, debt review, contractual claims
2. Labour Law — unfair dismissal, CCMA processes, workplace disputes, retrenchment
3. Criminal Defence — bail, rights upon arrest, trial processes
4. Family Law — divorce, custody, maintenance, domestic violence protection
5. Commercial Law — company formation, contracts, regulatory compliance
6. Estate Planning — wills, trusts, deceased estates, legacy protection

PRICING (for referral purposes):
- Civil Litigation Plan: R99/month
- Labour Law Plan: R99/month
- Extensive Cover Plan: R139/month (all practice areas)

If the user asks about pricing or wants to sign up, recommend they use the platform to create an account or book a consultation.`;

const INTAKE_SYSTEM_PROMPT = `You are a South African legal intake AI assistant for Infinity Legal SA. Analyze the client's legal matter and provide:

1) **Case Summary** - A brief, clear summary of the legal matter described
2) **Legal Area(s)** - The area(s) of South African law involved (e.g. Family Law, Criminal Defence, Civil Litigation, Conveyancing, Estate Planning, Corporate/Commercial, Debt Collection, Labour Law, Personal Injury)
3) **Recommended Next Steps** - Practical steps the client should consider taking
4) **Estimated Urgency Level** - One of: low, medium, high, or critical
5) **Recommended Plan** - Whether the matter might qualify for:
   - Civil Legal Plan (R99/month) - covers civil litigation, debt collection, conveyancing
   - Labour Legal Plan (R99/month) - covers labour disputes, unfair dismissal, workplace issues
   - Extensive Legal Plan (R139/month) - covers all areas including family law, criminal defence, corporate matters

Be professional, empathetic, and concise. Respond in a structured format with clear headings. Always remind them this is not formal legal advice and they should consult with an attorney for specific guidance.

POPIA NOTICE: This analysis is generated by AI. The client's personal information is processed in accordance with the Protection of Personal Information Act (POPIA). No sensitive personal data is stored by the AI system.`;

const SUMMARIZE_SYSTEM_PROMPT = `You are a legal document summarizer for Infinity Legal SA, a South African law firm. Summarize the provided legal document clearly and accurately.

Requirements:
- Provide a concise executive summary (2-3 sentences)
- List key legal issues and provisions
- Identify parties involved (redact sensitive details with [PARTY A], [PARTY B])
- Highlight important dates, deadlines, or time-sensitive matters
- Note any SA-specific legal references (acts, regulations, case law)
- Flag any potential risks or areas requiring attention
- Use South African legal terminology correctly

POPIA NOTICE: This document summary is AI-generated. All personal information is processed in accordance with POPIA. Do not include full ID numbers, bank details, or other sensitive PII in the summary.`;

const MEMO_SYSTEM_PROMPT = `You are a legal memo drafter for Infinity Legal SA, a South African law firm. Generate a professional legal memorandum based on the provided facts and legal issues.

Format the memo with these sections:
1. **TO / FROM / DATE / RE** — Standard memo header
2. **Question Presented** — The specific legal question(s)
3. **Brief Answer** — Yes/No with short explanation
4. **Discussion** — Analysis of relevant SA law, statutes, and case law
5. **Conclusion** — Summary and recommendations

Requirements:
- Reference relevant South African legislation (Constitution, LRA, BCEA, NCA, POPIA, CPA, etc.)
- Use proper legal citation format for SA cases and statutes
- Be objective and thorough in your analysis
- Note any uncertainties or areas requiring further research
- Include a POPIA compliance note if personal data is involved

IMPORTANT: This is a draft memo and does not constitute formal legal advice. It should be reviewed by a qualified attorney before reliance.`;

const TRANSLATE_SYSTEM_PROMPT = `You are a legal translator for Infinity Legal SA, specializing in translating legal text between South Africa's 11 official languages. 

South African official languages:
- English (en), Afrikaans (af), isiZulu (zu), isiXhosa (xh), Sesotho (st),
- Setswana (tn), Xitsonga (ts), Sepedi (nso), Tshivenda (ve), siSwati (ss), isiNdebele (nr)

Requirements:
- Preserve legal meaning and accuracy across languages
- Use formal legal register appropriate for each language
- Where a direct legal term doesn't exist in the target language, use the English term in brackets
- Maintain proper legal formatting and structure
- Note any cultural or linguistic nuances that may affect interpretation
- Always include a disclaimer that the translation is AI-generated and should be verified by a qualified legal translator

POPIA NOTICE: Translated documents may contain personal information processed under POPIA. Ensure proper handling of all personal data.`;

const RISK_ASSESSMENT_SYSTEM_PROMPT = `You are a legal risk assessor for Infinity Legal SA. Analyze the described legal matter and assess the risk level.

Provide:
1) **Risk Level** — One of: LOW, MEDIUM, HIGH, CRITICAL
2) **Risk Factors** — Key factors contributing to the risk assessment
3) **Potential Outcomes** — Likely best-case and worst-case scenarios
4) **Time Sensitivity** — Whether urgent action is required and why
5) **Cost Implications** — Estimated complexity and potential costs (qualitative only)
6) **Recommendation** — Suggested next steps and urgency

Consider South African legal context including:
- Court system capacity and timelines
- CCMA processes and time limits (30 days for unfair dismissal referral)
- Prescription periods for various claims
- Criminal procedure time limits (bail, appearance)
- Family law urgency (domestic violence, child welfare)

POPIA NOTICE: This risk assessment is AI-generated and does not constitute legal advice. All information is processed in accordance with POPIA.`;

const NEXT_STEPS_SYSTEM_PROMPT = `You are a legal advisor for Infinity Legal SA. Based on the case information provided, suggest practical next steps for the client.

For each step, include:
- **Action** — What needs to be done
- **Urgency** — Immediate / Within 7 days / Within 30 days / When convenient
- **Who** — Who should take this action (client, attorney, both)
- **Details** — Specific guidance on how to proceed
- **SA Context** — Any South African-specific considerations (e.g. CCMA deadlines, court filing requirements)

Also include:
- Documents or evidence the client should gather
- Deadlines that must not be missed
- Whether a consultation with an attorney is recommended
- A cost estimate range if appropriate

POPIA NOTICE: These suggestions are AI-generated and do not constitute formal legal advice. Consult with an attorney for case-specific guidance.`;

// ============================================
// LEGAL CHAT — Multi-turn conversation
// ============================================

export interface LegalChatOptions extends LLMChatOptions {
  sessionId: string;
}

export async function legalChat(
  userMessage: string,
  options: LegalChatOptions
): Promise<LLMChatResult> {
  const { sessionId, ...llmOptions } = options;

  // Get or create conversation
  const messages = getConversation(sessionId, LEGAL_CHAT_SYSTEM_PROMPT);

  // Add user message
  messages.push({ role: 'user', content: userMessage });

  // Trim if needed
  const trimmed = trimMessages(messages);

  // Call LLM
  const result = await llmChat(trimmed, {
    ...llmOptions,
    cache: false, // Don't cache conversational turns
    systemPrompt: LEGAL_CHAT_SYSTEM_PROMPT,
  });

  // Add assistant response to history
  trimmed.push({ role: 'assistant', content: result.content });

  // Save conversation
  updateConversation(sessionId, trimmed);

  return result;
}

// ============================================
// INTAKE ANALYSIS
// ============================================

export interface IntakeAnalysisInput {
  name: string;
  caseType: string;
  description: string;
  urgency?: string;
}

export async function analyzeIntake(input: IntakeAnalysisInput): Promise<LLMChatResult> {
  const messages: LLMMessage[] = [
    { role: 'system', content: INTAKE_SYSTEM_PROMPT },
    {
      role: 'user',
      content: `Please analyze the following legal matter:\n\n**Client Name:** ${input.name}\n**Case Type:** ${input.caseType}\n**Urgency:** ${input.urgency || 'Not specified'}\n**Description:** ${input.description}`,
    },
  ];

  return llmChat(messages, {
    cache: false,
    temperature: 0.5, // More deterministic for intake analysis
    maxTokens: 2048,
    systemPrompt: INTAKE_SYSTEM_PROMPT,
  });
}

// ============================================
// DOCUMENT SUMMARIZATION
// ============================================

export interface SummarizeInput {
  content: string;
  documentType?: string;
}

export async function summarizeDocument(input: SummarizeInput): Promise<LLMChatResult> {
  const docTypeNote = input.documentType
    ? `\n\nDocument type: ${input.documentType}`
    : '';

  const messages: LLMMessage[] = [
    { role: 'system', content: SUMMARIZE_SYSTEM_PROMPT },
    {
      role: 'user',
      content: `Please summarize the following legal document:${docTypeNote}\n\n---\n${input.content}\n---`,
    },
  ];

  return llmChat(messages, {
    cache: true,
    cacheTtl: 60 * 60 * 1000, // 1 hour cache for summaries
    temperature: 0.3, // Low temperature for factual summarization
    maxTokens: 2048,
    systemPrompt: SUMMARIZE_SYSTEM_PROMPT,
  });
}

// ============================================
// LEGAL MEMO GENERATION
// ============================================

export interface MemoInput {
  facts: string;
  issues: string;
  jurisdiction?: string;
}

export async function generateLegalMemo(input: MemoInput): Promise<LLMChatResult> {
  const messages: LLMMessage[] = [
    { role: 'system', content: MEMO_SYSTEM_PROMPT },
    {
      role: 'user',
      content: `Please draft a legal memorandum based on the following:\n\n**Facts:**\n${input.facts}\n\n**Legal Issues:**\n${input.issues}${input.jurisdiction ? `\n\n**Jurisdiction:** ${input.jurisdiction}` : ''}`,
    },
  ];

  return llmChat(messages, {
    cache: false,
    temperature: 0.5,
    maxTokens: 4096,
    systemPrompt: MEMO_SYSTEM_PROMPT,
  });
}

// ============================================
// LEGAL TRANSLATION (SA 11 official languages)
// ============================================

export interface TranslateInput {
  text: string;
  targetLanguage: string;
  sourceLanguage?: string;
}

export const SA_LANGUAGES: Record<string, string> = {
  en: 'English',
  af: 'Afrikaans',
  zu: 'isiZulu',
  xh: 'isiXhosa',
  st: 'Sesotho',
  tn: 'Setswana',
  ts: 'Xitsonga',
  nso: 'Sepedi',
  ve: 'Tshivenda',
  ss: 'siSwati',
  nr: 'isiNdebele',
};

export async function translateLegal(input: TranslateInput): Promise<LLMChatResult> {
  const targetName = SA_LANGUAGES[input.targetLanguage] || input.targetLanguage;
  const sourceNote = input.sourceLanguage
    ? ` from ${SA_LANGUAGES[input.sourceLanguage] || input.sourceLanguage}`
    : '';

  const messages: LLMMessage[] = [
    { role: 'system', content: TRANSLATE_SYSTEM_PROMPT },
    {
      role: 'user',
      content: `Translate the following legal text${sourceNote} to ${targetName}. Preserve all legal meaning, formatting, and structure:\n\n---\n${input.text}\n---`,
    },
  ];

  return llmChat(messages, {
    cache: true,
    cacheTtl: 2 * 60 * 60 * 1000, // 2 hour cache for translations
    temperature: 0.2, // Very low temperature for translation accuracy
    maxTokens: 4096,
    systemPrompt: TRANSLATE_SYSTEM_PROMPT,
  });
}

// ============================================
// CASE RISK ASSESSMENT
// ============================================

export interface RiskAssessmentInput {
  description: string;
  caseType?: string;
}

export async function assessCaseRisk(input: RiskAssessmentInput): Promise<LLMChatResult> {
  const caseTypeNote = input.caseType
    ? `\n**Case Type:** ${input.caseType}`
    : '';

  const messages: LLMMessage[] = [
    { role: 'system', content: RISK_ASSESSMENT_SYSTEM_PROMPT },
    {
      role: 'user',
      content: `Assess the legal risk for the following matter:${caseTypeNote}\n\n**Description:** ${input.description}`,
    },
  ];

  return llmChat(messages, {
    cache: true,
    cacheTtl: 15 * 60 * 1000, // 15 min cache
    temperature: 0.4,
    maxTokens: 2048,
    systemPrompt: RISK_ASSESSMENT_SYSTEM_PROMPT,
  });
}

// ============================================
// SUGGEST NEXT STEPS
// ============================================

export interface NextStepsInput {
  caseData: string;
  caseType?: string;
  urgency?: string;
}

export async function suggestNextSteps(input: NextStepsInput): Promise<LLMChatResult> {
  const caseTypeNote = input.caseType ? `\n**Case Type:** ${input.caseType}` : '';
  const urgencyNote = input.urgency ? `\n**Urgency:** ${input.urgency}` : '';

  const messages: LLMMessage[] = [
    { role: 'system', content: NEXT_STEPS_SYSTEM_PROMPT },
    {
      role: 'user',
      content: `Suggest next steps for the following case:${caseTypeNote}${urgencyNote}\n\n**Case Information:** ${input.caseData}`,
    },
  ];

  return llmChat(messages, {
    cache: true,
    cacheTtl: 15 * 60 * 1000, // 15 min cache
    temperature: 0.5,
    maxTokens: 2048,
    systemPrompt: NEXT_STEPS_SYSTEM_PROMPT,
  });
}

// ============================================
// CLEAR CONVERSATION
// ============================================

export function clearLegalChat(sessionId: string): void {
  clearConversation(sessionId);
}
