apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infinity-legal-sqlite-pvc
  namespace: infinity-legal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
